include_guard(GLOBAL)

function(_version_generate_header version prefix output repo_dir)
    if(NOT version)
        set(version "0.0.0.0")
    endif()

    string(REPLACE "." ";" _parts "${version}")
    list(LENGTH _parts _n)

    set(_v0 0)
    set(_v1 0)
    set(_v2 0)
    set(_v3 0)
    if(_n GREATER 0)
        list(GET _parts 0 _v0)
    endif()
    if(_n GREATER 1)
        list(GET _parts 1 _v1)
    endif()
    if(_n GREATER 2)
        list(GET _parts 2 _v2)
    endif()
    if(_n GREATER 3)
        list(GET _parts 3 _v3)
    endif()

    set(_git_hash "unknown")
    set(_git_hash_full "unknown")
    set(_git_branch "unknown")
    set(_git_dirty 0)
    set(_git_tag "")

    find_program(_git_exe NAMES git)
    if(_git_exe AND EXISTS "${repo_dir}/.git")
        execute_process(
                COMMAND "${_git_exe}" rev-parse --short=12 HEAD
                WORKING_DIRECTORY "${repo_dir}"
                OUTPUT_VARIABLE _tmp
                OUTPUT_STRIP_TRAILING_WHITESPACE
                ERROR_QUIET
                RESULT_VARIABLE _rc)
        if(_rc EQUAL 0 AND _tmp)
            set(_git_hash "${_tmp}")
        endif()

        execute_process(
                COMMAND "${_git_exe}" rev-parse HEAD
                WORKING_DIRECTORY "${repo_dir}"
                OUTPUT_VARIABLE _tmp
                OUTPUT_STRIP_TRAILING_WHITESPACE
                ERROR_QUIET
                RESULT_VARIABLE _rc)
        if(_rc EQUAL 0 AND _tmp)
            set(_git_hash_full "${_tmp}")
        endif()

        execute_process(
                COMMAND "${_git_exe}" rev-parse --abbrev-ref HEAD
                WORKING_DIRECTORY "${repo_dir}"
                OUTPUT_VARIABLE _tmp
                OUTPUT_STRIP_TRAILING_WHITESPACE
                ERROR_QUIET
                RESULT_VARIABLE _rc)
        if(_rc EQUAL 0 AND _tmp)
            set(_git_branch "${_tmp}")
        endif()

        execute_process(
                COMMAND "${_git_exe}" status --porcelain
                WORKING_DIRECTORY "${repo_dir}"
                OUTPUT_VARIABLE _tmp
                OUTPUT_STRIP_TRAILING_WHITESPACE
                ERROR_QUIET
                RESULT_VARIABLE _rc)
        if(_rc EQUAL 0 AND _tmp)
            set(_git_dirty 1)
        endif()

        execute_process(
                COMMAND "${_git_exe}" describe --tags --exact-match HEAD
                WORKING_DIRECTORY "${repo_dir}"
                OUTPUT_VARIABLE _tmp
                OUTPUT_STRIP_TRAILING_WHITESPACE
                ERROR_QUIET
                RESULT_VARIABLE _rc)
        if(_rc EQUAL 0 AND _tmp)
            set(_git_tag "${_tmp}")
        endif()
    endif()

    string(TIMESTAMP _build_date "%Y-%m-%d")

    get_filename_component(_header_name "${output}" NAME_WE)
    string(TOUPPER "${_header_name}" _header_name)
    string(REGEX REPLACE "[^A-Z0-9]" "_" _header_name "${_header_name}")
    set(_guard "__${prefix}_${_header_name}_HEADER_FILE__")

    set(_content
"/* Generated by version.cmake - do not edit by hand. */
#ifndef ${_guard}
#define ${_guard}

#define ${prefix}_VERSION_MAJOR     ${_v0}
#define ${prefix}_VERSION_MINOR     ${_v1}
#define ${prefix}_VERSION_PATCH     ${_v2}
#define ${prefix}_VERSION_BUILD     ${_v3}
#define ${prefix}_VERSION_COMMA     ${_v0},${_v1},${_v2},${_v3}
#define ${prefix}_VERSION_STRING    \"${_v0}.${_v1}.${_v2}.${_v3}\"

#define ${prefix}_GIT_HASH          \"${_git_hash}\"
#define ${prefix}_GIT_HASH_FULL     \"${_git_hash_full}\"
#define ${prefix}_GIT_BRANCH        \"${_git_branch}\"
#define ${prefix}_GIT_DIRTY         ${_git_dirty}
#define ${prefix}_GIT_TAG           \"${_git_tag}\"

#define ${prefix}_BUILD_DATE        \"${_build_date}\"

#endif /* ${_guard} */
")

    set(_should_write TRUE)
    if(EXISTS "${output}")
        file(READ "${output}" _existing)
        if(_existing STREQUAL _content)
            set(_should_write FALSE)
        endif()
    endif()

    if(_should_write)
        get_filename_component(_dir "${output}" DIRECTORY)
        if(_dir)
            file(MAKE_DIRECTORY "${_dir}")
        endif()
        file(WRITE "${output}" "${_content}")
    endif()
endfunction()

function(generate_version_header)
    cmake_parse_arguments(_arg "" "VERSION;PREFIX;OUTPUT;REPO_DIR" "" ${ARGN})

    if(NOT _arg_PREFIX)
        set(_arg_PREFIX "APP")
    endif()
    if(NOT _arg_OUTPUT)
        set(_arg_OUTPUT "${CMAKE_BINARY_DIR}/gen/git_version.h")
    endif()
    if(NOT _arg_REPO_DIR)
        set(_arg_REPO_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    endif()

    if(NOT _arg_VERSION)
        if(PROJECT_VERSION)
            set(_arg_VERSION "${PROJECT_VERSION}")
        else()
            set(_arg_VERSION "0.0.0.0")
        endif()
    endif()

    _version_generate_header(
            "${_arg_VERSION}"
            "${_arg_PREFIX}"
            "${_arg_OUTPUT}"
            "${_arg_REPO_DIR}")
endfunction()
